In [ ]:
import tensorflow as tf
from tensorflow.keras.activations import sigmoid
 
input_array = tf.constant([-1, 0, 1], dtype=tf.float32)
print (sigmoid(input_array))

tf.Tensor([0.26894143 0.5        0.7310586 ], shape=(3,), dtype=float32)


In [ ]:
import tensorflow as tf
from tensorflow.keras.activations import tanh

input_array = tf.constant([-1, 0, 1], dtype=tf.float32)
print (tanh(input_array))

tf.Tensor([-0.7615942  0.         0.7615942], shape=(3,), dtype=float32)


In [ ]:
import tensorflow as tf
from tensorflow.keras.activations import relu
 
input_array = tf.constant([-1, 0, 1], dtype=tf.float32)
print (relu(input_array))

tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)


In [ ]:
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras.layers import Dense, Input, Flatten, Conv2D, BatchNormalization, MaxPool2D
from tensorflow.keras.models import Model
 
(trainX, trainY), (testX, testY) = keras.datasets.cifar10.load_data()
 
input_layer = Input(shape=(32,32,3,))
x = Conv2D(filters=6, kernel_size=(5,5), padding="same", activation="relu")(input_layer)
x = MaxPool2D(pool_size=(2,2))(x)
x = Conv2D(filters=16, kernel_size=(5,5), padding="same", activation="relu")(x)
x = MaxPool2D(pool_size=(2, 2))(x)
x = Conv2D(filters=120, kernel_size=(5,5), padding="same", activation="relu")(x)
x = Flatten()(x)
x = Dense(units=84, activation="relu")(x)
x = Dense(units=10, activation="softmax")(x)
 
model = Model(inputs=input_layer, outputs=x)
 
print(model.summary())
 
model.compile(optimizer="adam", loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics="acc")
 
history = model.fit(x=trainX, y=trainY, batch_size=256, epochs=10, validation_data=(testX, testY))

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 32, 32, 3)]       0         
                                                                 
 conv2d_3 (Conv2D)           (None, 32, 32, 6)         456       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 16, 16, 6)        0         
 2D)                                                             
                                                                 
 conv2d_4 (Conv2D)           (None, 16, 16, 16)        2416      
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 8, 8, 16)         0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 8, 8, 120)         4812